ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS cpf VARCHAR(14);
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS telefone VARCHAR(20);
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS data_nascimento DATE;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS endereco TEXT;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS crp VARCHAR(20);
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS registro_e_psi VARCHAR(50);
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS abordagem VARCHAR(100);
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS area_de_atuacao VARCHAR(100);
