ALTER TABLE agendamentos DROP CONSTRAINT IF EXISTS agendamentos_modalidade_repasse_check;
--;;
ALTER TABLE agendamentos DROP COLUMN IF EXISTS repasse_calculado_em;
--;;
ALTER TABLE agendamentos DROP COLUMN IF EXISTS valor_fixo_repasse_aplicado;
--;;
ALTER TABLE agendamentos DROP COLUMN IF EXISTS percentual_repasse_aplicado;
--;;
ALTER TABLE agendamentos DROP COLUMN IF EXISTS modalidade_repasse_aplicada;
--;;
ALTER TABLE usuarios DROP CONSTRAINT IF EXISTS usuarios_regra_repasse_check;
--;;
ALTER TABLE usuarios DROP CONSTRAINT IF EXISTS usuarios_modalidade_repasse_check;
--;;
ALTER TABLE usuarios DROP COLUMN IF EXISTS valor_fixo_repasse;
--;;
ALTER TABLE usuarios DROP COLUMN IF EXISTS percentual_repasse;
--;;
ALTER TABLE usuarios DROP COLUMN IF EXISTS modalidade_repasse;
