DROP INDEX IF EXISTS idx_usuarios_clinica_papel;
--;;
DROP INDEX IF EXISTS idx_prontuarios_agendamento;
--;;
DROP INDEX IF EXISTS idx_prontuarios_paciente_data;
--;;
DROP INDEX IF EXISTS idx_pacientes_psicologo;
--;;
DROP INDEX IF EXISTS idx_pacientes_clinica_status;
--;;
DROP INDEX IF EXISTS idx_bloqueios_recorrencia;
--;;
DROP INDEX IF EXISTS idx_bloqueios_clinica_psi_periodo;
--;;
DROP INDEX IF EXISTS idx_agendamentos_status_pendente;
--;;
DROP INDEX IF EXISTS idx_agendamentos_paciente_data;
--;;
DROP INDEX IF EXISTS idx_agendamentos_clinica_psi_data;
--;;
DROP INDEX IF EXISTS idx_agendamentos_clinica_data;
